version: '3.8'

services:
  whatsapp:
    build: .
    container_name: whatsapp_server
    ports:
      - "8000:8000"
    volumes:
      - ./auth:/app/auth
      - ./logs:/app/logs
    restart: unless-stopped
